### ISSUE TITLE
All tests are failing on Travis/CI tonight

### ISSUE THREAD

**Issue by stopfstedt** [ilios/common#67]
the culprit is always the same:

```
not ok 184 Chrome 60.0 - Integration | Component | week glance: changing passed properties re-renders
    ---
        actual: >
            false
        expected: >
            true
        stack: >
                at Class.getEvents (http://localhost:7357/assets/tests.js:3082:30)
                at Class._callee$ (http://localhost:7357/assets/vendor.js:132388:45)
                at tryCatch (http://localhost:7357/assets/vendor.js:11369:40)
                at Generator.invoke [as _invoke] (http://localhost:7357/assets/vendor.js:11607:22)
                at Generator.prototype.(anonymous function) [as next] (http://localhost:7357/assets/vendor.js:11421:21)
                at step (http://localhost:7357/assets/vendor.js:132295:32)
        message: >
            failed, expected argument to be truthy, was: false
        Log: |
    ...
```

this test is (still) passing just fine locally. 

i suspect some date/time shenanigans.

**Comment by stopfstedt** [comment]
as of this morning, this test is now failing locally too.

**Comment by jrjohnson** [comment]
This I think this is a feature to keep us from working on weekends!
