### ISSUE TITLE
Calendar ICS link throws an error

### ISSUE THREAD

**Issue by saschaben** [ilios/common#7]
In the current release version, attempting to grab the ics link from the calendar throws the following error:

```
Compile Error: ics-feed is not a helper

Error: Compile Error: ics-feed is not a helper
    at t.compile (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4573:82)
    at t.compile (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4483:234)
    at t.e.compileStatement (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4268:208)
    at t.compile (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4280:6)
    at a.compile (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:3928:41)
    at e.invokeBlock (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4654:201)
    at t.evaluate (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4234:153)
    at e.execute (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4653:112)
    at e.resume (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4650:474)
    at t.handleException (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4689:514) 
```

**Comment by stopfstedt** [comment]
it appears tha the `ics-feed` did not get moved from the now retired calendar repo into common. 

working on it.
